name             'cronapt-cookbook'
maintainer       'Promet Solutions, Inc.'
maintainer_email 'gregpalmier@gmail.com'
license          'All rights reserved'
description      'Installs/Configures cronapt-cookbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'
depends		 'apt'
depends		 'cron'
depends		 'postfix'
